Header
mate-academy/Kickstarter pull request #115
Opened 2021-11-01 16:27 UTC by Veronika-Korona

[DEMO LINK](https://veronika-korona.github.io/Kickstarter/)

Just header. Couldn't fix the images and haven't add the fonts yet.

2021-11-04 10:29 UTC, dmtrhrytsak commented
Make the menu to stick to the top of the page so that when users would be scrolling down they had access to navigation links 👀

![image](https://user-images.githubusercontent.com/72860434/140298367-4f5bd803-28cf-4c2f-8995-4ea45fc63633.png)

2021-11-04 10:30 UTC, dmtrhrytsak commented
The width of the testimonial's review should be much smaller, check the Figma!

![image](https://user-images.githubusercontent.com/72860434/140298584-04ee72db-f9a5-4bd4-8f9b-5a49cc58441b.png)

2021-11-04 10:32 UTC, dmtrhrytsak commented
Your quotes seem to be minding their own business, don't let them cut off like this)

![image](https://user-images.githubusercontent.com/72860434/140298863-196c6d1d-b2c3-49f6-9a5e-42f9c200a5e2.png)

2021-11-04 10:33 UTC, dmtrhrytsak approved these changes

2021-11-04 11:58 UTC, aionova requested changes
- make all the buttons and links do something and lead you somewhere, and have cursor: pointer
- when I hover on one of the items, others are not supposed to move
<img width="599" alt="Screenshot 2021-11-04 at 13 53 45" src="https://user-images.githubusercontent.com/68023426/140309129-fec35778-f43e-4c41-8aa1-b6285ad3406d.png">
- social media links in the footer should be real links to social medias of crazy baby
- on iphone 5 content doesn't fit in its parent
<img width="593" alt="Screenshot 2021-11-04 at 13 56 09" src="https://user-images.githubusercontent.com/68023426/140309410-eb7f146d-1391-4ac2-a7c5-c3ba10495bce.png">

2021-11-05 08:41 UTC, aionova requested changes
- you didn't fix the social media links. I wrote about them in a previous comment
<img width="645" alt="Screenshot 2021-11-05 at 10 22 40" src="https://user-images.githubusercontent.com/68023426/140480306-5c405fdd-01a2-4b9f-9ccc-86b7ee4ade73.png">
- on ipad Pro and ipad content doesn't fit in its parent
<img width="154" alt="Screenshot 2021-11-05 at 10 35 45" src="https://user-images.githubusercontent.com/68023426/140481866-bc32545c-554f-401a-a44a-b001246db817.png">
- this thing needs to be wider 
<img width="162" alt="Screenshot 2021-11-05 at 10 36 44" src="https://user-images.githubusercontent.com/68023426/140481986-2e26455e-1839-4063-9568-7f4977774a87.png">

2021-11-05 16:29 UTC, aionova requested changes
- social links should open in a new tab
- on iphone 5 content still doesn't fit(

2021-11-08 13:25 UTC, illiarerun requested changes
Good job 🔥  Let's work on more fixes now:

- fix scroll under menu:
![image](https://user-images.githubusercontent.com/37161315/140749088-ab5bdc2b-b630-452c-af2d-927c95b55ac7.png)

- social media icons are a bit offcentered, make sure to fix it:
![image](https://user-images.githubusercontent.com/37161315/140749212-ea06f83e-6ca8-45a0-815d-08b7bf8575af.png)

- fix menu for mobile landscape mode:
![image](https://user-images.githubusercontent.com/37161315/140749579-d509700c-4547-4eb0-bc47-3b9f0ecf17b8.png)

- fonts on placeholders and plain text are totally different, that's not okay:
![image](https://user-images.githubusercontent.com/37161315/140749834-b2f2c78b-2076-412e-aa0b-04a0ddeead25.png)

2021-11-09 08:32 UTC, illiarerun approved these changes
Good job 🔥 Make sure to fix this:

2021-11-09 08:32 UTC, illiarerun commented on src/styles/blocks/page.scss
> +    z-index: 10;
z-index is not the best solution for turning off the scroll, you can use the fix from Miami for that purpose. Also `10`, that's a lot))

2025-01-07 19:23 UTC, closed without merging