Kickstarter
mate-academy/Kickstarter pull request #19
Opened 2020-09-13 13:49 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/Kickstarter/)

2020-09-18 13:16 UTC, goncharukop commented
https://prnt.sc/ujjdwq - навігація не по фігмі, має бути більш центрована
https://prnt.sc/ujjfa8 або 4 або 2, не 3
https://prnt.sc/ujjgcp - великими
https://prnt.sc/ujjhxb - не по фігмі
https://prnt.sc/ujjj1u - не по фігмі
https://prnt.sc/ujjjkh - не по фігмі
https://prnt.sc/ujjk7j - не по фігмі
https://prnt.sc/ujjlae - не по фігмі і не видно плейсхолдер
https://prnt.sc/ujjpkt - тут інша назва
для 768рх:
https://prnt.sc/ujjnd5 - не по фігмі
https://prnt.sc/ujjqn4 - не по фігмі
https://prnt.sc/ujjrfe  - не по фігмі
для 300рх:
https://prnt.sc/ujjt85 має зникати навігація і з'являтись бургер і кнопка купити
https://prnt.sc/ujjtpk - текст виходить за екран
https://prnt.sc/ujjuip - має залишитись 1 картка
https://prnt.sc/ujjv2k   - не по фігмі
https://prnt.sc/ujjveb - має залишитись 1 картка
https://prnt.sc/ujjwr1   - не по фігмі

2020-09-18 13:17 UTC, goncharukop requested changes
код ще не дивився

2020-09-21 09:27 UTC, goncharukop approved these changes

2020-09-21 12:08 UTC, solaryasha requested changes
Зробив [ревью](https://www.loom.com/share/02d3d39da15a450aa0bfa147072ae454) на твій лендінг. Знайшов кілька неточностей

2020-09-21 17:58 UTC, andlap24 commented
> Зробив [ревью](https://www.loom.com/share/02d3d39da15a450aa0bfa147072ae454) на твій лендінг. Знайшов кілька неточностей

стосовно пробілів у textarea...вже дізнався, що є такий баг. Але як пофіксити ніяк не можу знайти рішення. Глянь, будь-ласка, index.html 318:13.

2020-09-22 08:13 UTC, solaryasha requested changes
+ Перевір адаптивність
<img width="714" alt="Screenshot 2020-09-22 at 11 13 03" src="https://user-images.githubusercontent.com/32794096/93858305-9ca3ee00-fcc4-11ea-879e-e749760b2e71.png">

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +              alt=""
Не залишай пустий `alt` атрибут

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +              <li class="header_heading-item">
Це елемент чи блок чи модифікатор ?

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +            </h1>
```suggestion
            <h1>
              Futuristic
              Wireless
              Speaker
            </h1>
```

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +            </p>
```suggestion
            <p>
              Luna’s performance is balanced and
              smooth in all frequency ranges which
              makes the music both naturally
              pleasant and distinctly more layered.
            </p>
```

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +        <img src="./images/icons/shopping.png" alt="">
Пустий `alt`

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +                alt="">
Пустий `alt` і неправильне форматування.

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +                alt="">
Пустий alt і неправильне форматування.

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +                alt="">
Пустий alt і неправильне форматування.

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +                alt="">
Пустий alt і неправильне форматування.

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +              alt=""
Пустий альт

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +                alt=""
Пустий альт

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +                  <br>
Краще без використання `br` тега, а CSS-ом

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +            <div class="technology__description technology__description--10">+</div>
Модифікатори мають нести якусь унікальність, а не порядковий номер

2020-09-22 08:13 UTC, solaryasha commented on src/index.html
> +            </textarea>
Пофіксиш свій баг з полем
```suggestion
            ></textarea>
```

2020-10-01 14:31 UTC, Vladimir-Beliy commented
плейсхолдеры в разных стилях
![image](https://user-images.githubusercontent.com/60401137/94822558-78a28400-040b-11eb-9db9-f9b76f74446b.png)

фейсбук чуток больше
![image](https://user-images.githubusercontent.com/60401137/94822660-8f48db00-040b-11eb-9057-cf91dd0ca2f2.png)

текст очень близко
![image](https://user-images.githubusercontent.com/60401137/94822811-bd2e1f80-040b-11eb-9958-68441b4c5bf4.png)

не на одном уровне
![image](https://user-images.githubusercontent.com/60401137/94822837-c7501e00-040b-11eb-847d-64b2d726877e.png)

2020-10-01 14:37 UTC, Vladimir-Beliy requested changes
сделай это место как на фигме
![image](https://user-images.githubusercontent.com/60401137/94823504-991f0e00-040c-11eb-8edc-bfa92a809ae9.png)

2020-10-01 14:37 UTC, Vladimir-Beliy commented on src/index.html
> +        <div class="header-heading">
зачем тебе тут двойное название?

2020-10-01 14:37 UTC, Vladimir-Beliy commented on src/index.html
> +          <div class="presentation">
элемент за блоком

2020-10-01 14:37 UTC, Vladimir-Beliy commented on src/index.html
> +                alt="">
![image](https://user-images.githubusercontent.com/60401137/94823269-59f0bd00-040c-11eb-81a3-a3a0eb851088.png)
почему не исправил?

2020-10-01 14:37 UTC, Vladimir-Beliy commented on src/index.html
> +                alt="">
![image](https://user-images.githubusercontent.com/60401137/94823327-683ed900-040c-11eb-82cd-b0e782fd5d20.png)

2020-10-01 14:37 UTC, Vladimir-Beliy commented on src/index.html
> +                class="about__design-image-small"
модификатор не может быть один

2020-10-01 14:37 UTC, Vladimir-Beliy commented on src/index.html
> +            class="form contact__form"
```suggestion
            class="contact__form form"
```

2020-10-01 14:40 UTC, Vladimir-Beliy commented
не посредине 
![image](https://user-images.githubusercontent.com/60401137/94823867-05017680-040d-11eb-800b-cfa79834687f.png)

вертикальная прокрутка
![Uploading image.png…]()

нужно поработать еще над адаптацией

2020-10-06 11:03 UTC, andlap24 commented on src/index.html
> +                class="about__design-image-small"
это тройное название, у меня 2 бэкграунда на десктоп и мобайл версии. Но путаница из-за имени, исправлю

2020-10-15 11:47 UTC, danheim approved these changes

2026-02-15 13:15 UTC, closed without merging