installed npm, created empty header
mate-academy/Kickstarter pull request #225
Opened 2022-09-05 08:14 UTC by SerhiiRomaniukWD

2022-09-05 12:12 UTC, SerhiiRomaniukWD commented
> _ No description provided. _

https://<your_account>.github.io/Kickstarter/

2022-09-06 13:03 UTC, OleksiiBlezniuk reviewed
Distance between nav and text is too big, image on mobile screens is too small

Keep working

2022-09-07 10:48 UTC, OleksiiBlezniuk reviewed
Text in this block should start from one line, check design
![Screenshot 2022-09-07 at 13 42 29](https://user-images.githubusercontent.com/84275496/188859405-d36ff62c-871f-498d-824e-b3b8e6ce4000.png)

This image shouldn't be cropped
![Screenshot 2022-09-07 at 13 48 03](https://user-images.githubusercontent.com/84275496/188860393-34ebec01-a1bc-453d-b312-887312d390f0.png)

2022-09-08 17:39 UTC, SerhiiRomaniukWD commented
> 

okey, thanks!I will fix it

2022-09-09 12:03 UTC, OleksiiBlezniuk requested changes
There should be more text lists in Features bloc, check design

Page shouldn't be reloaded after submit, also better to reset default autocompleted input styles, there is information about it in checklist

<img width="1314" alt="Screenshot 2022-09-09 at 14 51 04" src="https://user-images.githubusercontent.com/84275496/189343668-1373e74e-e4eb-45ad-8ddd-3197f24cc3cd.png">

Links to social medias should be opened in new tab

Remove paddings from `li` in burger menu, let distance between content and left of the page be consistent with page, now it looks strange

Also need to add close button to mobile menu, also fix this scroll

https://user-images.githubusercontent.com/84275496/189345749-9a2d60e6-4e5f-4078-991f-1eccd3ea6803.mov

2022-09-12 11:34 UTC, Andr1yK approved these changes

2025-05-25 17:24 UTC, closed without merging