First release. Landing without slider for phones
mate-academy/Kickstarter pull request #269
Opened 2023-01-16 14:46 UTC by read-my-code

[DEMO LINK](https://read-my-code.github.io/Kickstarter/)

2023-01-30 16:10 UTC, loralevitska requested changes
Keep up the good work! Some comments to fix:

1. Remove default background color after autocomplete 
![image](https://user-images.githubusercontent.com/70009205/215528090-cbba63f2-598a-4319-8c8d-490a5ead8de9.png)
2. After submit don't reload page (just send info to form and reset form). Fix it error (screenshot)
![image](https://user-images.githubusercontent.com/70009205/215528307-c5050ed5-58ba-4913-a74c-8d141d9d73fd.png)
3. Add padding-bottom to page 
![image](https://user-images.githubusercontent.com/70009205/215528928-695fcf62-437d-4bfb-b876-e67860bb7d1f.png)
4. Picture doesn't match with design 
![image](https://user-images.githubusercontent.com/70009205/215529447-432fc853-9a77-4771-a6d4-c660f78652cc.png)
5. Better add slider (If you have some problem ask advice in fe_chat) || just first create all the buttons that are in the design (all the text from all the sliders don't need to be added)
![image](https://user-images.githubusercontent.com/70009205/215529984-256b53bd-906d-486c-ab30-0c806e276f75.png)

If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-08-23 11:17 UTC, read-my-code commented
> 4. Picture doesn't match with design
>    ![image](https://user-images.githubusercontent.com/70009205/215529447-432fc853-9a77-4771-a6d4-c660f78652cc.png)

А якщо мені так більше подобається, все рівно міняти ?

2023-08-24 06:27 UTC, etojeDenys requested changes
you should show only this block on mobile
<img width="366" alt="image" src="https://github.com/mate-academy/Kickstarter/assets/70220667/1063899a-4387-4924-8bde-3f78aa2f7baa">

2023-08-25 14:40 UTC, loralevitska approved these changes
Good job! Check my comment for improvement
- make sure that all interactive elements have a cursor pointer on hover

2025-09-08 09:41 UTC, closed without merging