Kickstarter
mate-academy/Kickstarter pull request #330
Opened 2023-08-23 18:25 UTC by mykolahuryn

[DEMO LINK](https://mykolahuryn.github.io/Kickstarter/)

2023-08-23 20:04 UTC, mykolahuryn commented
вирішив дану проблему)

2023-08-24 06:52 UTC, maxim2310 requested changes
Great job overall! Just couple tiny things needs to be fixed before approval)

1. when i hover on it right text is jumping
![image](https://github.com/mate-academy/Kickstarter/assets/96265844/f7cd5981-b01e-4b8e-9e17-faff39c6a602)
2. need to remove background on autocomplete  
![image](https://github.com/mate-academy/Kickstarter/assets/96265844/b30af0d1-d84e-4d21-8a10-234d943e06d6)
3. and add validation on email field 
4. check out why after submitting form email field ask to fill in
5. i think menu must take all height 
![image](https://github.com/mate-academy/Kickstarter/assets/96265844/4bf6b700-5354-436d-8171-dd8f92a54df8)
6. 
![image](https://github.com/mate-academy/Kickstarter/assets/96265844/8a046530-aa0c-4e88-817d-fd8347aeb9e9)

2023-08-24 06:52 UTC, maxim2310 requested changes
.

2023-08-25 07:21 UTC, maxim2310 requested changes
Almost there) Just couple tiny things needs to be fixed

1. after submit form must to clean up 
2. on tablet in menu button and lang block are missing and font style different from mobile

2023-08-25 18:34 UTC, mykolahuryn commented
Дякую за зауваження. 
1.У мене чомусь працює очистка форми після відправки. Прикладаю відео.

https://github.com/mate-academy/Kickstarter/assets/95581971/c1486f29-6236-4f13-9d93-f5295623ed29

2. Якщо я правильно Вас зрозумів то ви написали що у  tablet версії в меню відсутні блок кнопки та мови. В дизайні так же само)
![photo_1](https://github.com/mate-academy/Kickstarter/assets/95581971/3c24bc48-2f81-408e-9dd5-eeaebc6d1124)
 і що font style відрізняється від мобільної версії, що на мій погляд також не так
 
![photo_2](https://github.com/mate-academy/Kickstarter/assets/95581971/4eff26b1-a283-445e-9602-f833475e0e4b)
![photo_3](https://github.com/mate-academy/Kickstarter/assets/95581971/7d53c975-8d8d-440a-8209-e3f81a092f29)
   
   
   Вибачаюсь якщо я Вас не правильно зрозумів. Дякую

2023-08-26 06:29 UTC, sTorba24 requested changes
You did amazing job! Almost fine, lets improve a little

Check input section on mobile, it has redundant right margin(also check icons)
![image](https://github.com/mate-academy/Kickstarter/assets/55200530/12d56777-1a17-4a9f-8e9f-1b9fd74fc829)

mockup
![image](https://github.com/mate-academy/Kickstarter/assets/55200530/e26847fb-6204-4d75-8773-d48a38b86291)

2023-09-04 09:19 UTC, mykolahuryn commented
запустив npm run deploy
чомусь в демо зміни не відображаються.

2023-09-04 15:12 UTC, VitaliyBondarenko1982 requested changes
Almost done.
Suggest to fix a couple more moments)
- add `resize: none` for textarea styles for prevent such behavior
![chrome-capture-2023-8-4 (1)](https://github.com/mate-academy/Kickstarter/assets/33029864/88391830-bc75-4708-b03b-007f7169004c)
- make custom scrollbar for textarea
https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp
![Screenshot from 2023-09-04 18-04-11](https://github.com/mate-academy/Kickstarter/assets/33029864/ea0c83fa-e8ce-495f-9527-62f8744e04bd)

2024-10-25 09:22 UTC, closed without merging