Kickstarter PR
mate-academy/Kickstarter pull request #95
Opened 2021-09-07 06:10 UTC by Rocketjet

[DEMO LINK](https://Rocketjet.github.io/Kickstarter/)

2021-09-10 16:10 UTC, OleksiiBlezniuk reviewed
Пока ошибок не вижу, продолжай работу над адаптивом

2021-09-10 16:15 UTC, Rocketjet commented
> Пока ошибок не вижу, продолжай работу над адаптивом

Цим і займаюсь не покладаючи рук)

2021-09-13 07:32 UTC, Rocketjet commented
TODO list:

швидкі фікси
1. Забрати ховер з перемикача мови, зробити активною, тобто жирним шрифтом, EN
2. Поправити ховер ефект для сабтайтла в моб версії (зробити коротшою виїжджаючу лінію)

глобальні фікси
1. Додати для кожної секції елементи page__section-__ для встановлення на них margin (по БЕМ)

дод. функціонал
1. Реалізувати версію для десктопа (в роботі)
2. Доробити меню на моб версії, по аналогії з Miami лендінгом (JS)
3. Зробити перегортання карток в двох блоках в моб версії (JS)

2021-09-14 09:10 UTC, Anna-Tkachenko requested changes
- Сверь с макетом расположение элементов в этой секции https://prnt.sc/1s5d4wu (надо выровнять)
- На сайте есть горизонтальная прокрутка - fix it https://prnt.sc/1s5dqxr
В остальном все хорошо

2021-09-14 10:23 UTC, Ihor-Karpyn approved these changes
LGTM

2024-05-29 15:32 UTC, closed without merging